services:
  db:
    image: mysql:8.0.28
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - .env.db
#    environment:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - data:/var/lib/mysql/
      - ./001_madup.sql:/docker-entrypoint-initdb.d/001_madup.sql
    restart: always

  web:
    build: .
#    dockerfile: Dockerfile
    command: >
      bash -c "python /code/manage.py migrate
      && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  data:
